[buildpack]
name = "Ruby"
ruby_version = "3.1.2"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  # get tokens for logging build tokens
  url = "https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
  dir = "."
  files = ["./.env"]
  [[publish.Vendor]]
  url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-3.1.2.tgz"
  dir = "vendor/ruby/cedar-14"
  [[publish.Vendor]]
  url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-16/ruby-3.1.2.tgz"
  dir = "vendor/ruby/heroku-16"
  [[publish.Vendor]]
  url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-3.1.2.tgz"
  dir = "vendor/ruby/heroku-18"
